name: Continuous Integration
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installing Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Building executable
        run: go build .

      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32.2
